server:
  port: '8080'
  error:
    include-stacktrace: never
spring:
  cache:
    cache-names:
      - buckets
    caffeine:
      spec: maximumSize=1000000,expireAfterAccess=3600s
  datasource:
    url: 'jdbc:postgresql://postgres:5432/ctf'
    username: ctf
    password: ctf
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#  cache:
#    jcache:
#      config: classpath:ehcache.xml

logging:
  level:
    org:
      springframework:
        security: INFO
ctfconfig:
  ctf-title: TAM-CTF
  flag-wrapper: CTF
  telegram-bot-enabled: false
  game-start-time: '2023-09-10T00:22:00'
  freeze-start-time: '2024-09-10T00:22:00'
  game-end-time: '2025-09-10T00:22:00'
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 10
              time: 1
              unit: minutes
  cache-to-use: jcache

jwt:
  secret: "SECRETSTRINGHSECRETSTRINGHERESECRETSTRINGHERESECRETSTRINGHERESECRETSTRINGHERESECRETSTRINGHERESECRETSTRINGHEREERE"
  lifetime: 600m